<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="My Sample Suite" duration-ms="8932" started-at="2019-12-20T20:24:29Z" finished-at="2019-12-20T20:24:38Z">
    <groups>
    </groups>
    <test name="Jenkins integration" duration-ms="8932" started-at="2019-12-20T20:24:29Z" finished-at="2019-12-20T20:24:38Z">
      <class name="Jenkins_new_Java.testing">
        <test-method status="FAIL" signature="getData()[pri:0, instance:Jenkins_new_Java.testing@79b4d0f]" name="getData" duration-ms="11" started-at="2019-12-20T14:24:29Z" finished-at="2019-12-20T14:24:29Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.fail(Assert.java:56)
	at Jenkins_new_Java.testing.getData(testing.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getData -->
        <test-method status="PASS" signature="login1()[pri:0, instance:Jenkins_new_Java.testing@79b4d0f]" name="login1" duration-ms="7570" started-at="2019-12-20T14:24:29Z" finished-at="2019-12-20T14:24:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
        <test-method status="PASS" signature="success()[pri:0, instance:Jenkins_new_Java.testing@79b4d0f]" name="success" duration-ms="0" started-at="2019-12-20T14:24:37Z" finished-at="2019-12-20T14:24:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- success -->
        <test-method status="PASS" signature="tear()[pri:0, instance:Jenkins_new_Java.testing@79b4d0f]" name="tear" is-config="true" duration-ms="1326" started-at="2019-12-20T14:24:37Z" finished-at="2019-12-20T14:24:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- Jenkins_new_Java.testing -->
    </test> <!-- Jenkins integration -->
  </suite> <!-- My Sample Suite -->
</testng-results>
